### ISSUE TITLE
GET  undefined symbol results in 500 Server error

### ISSUE THREAD

**Issue by RodneyRichardson** [fbarresi/SoftBeckhoff#1]
In the default server, calling [GET: /symbols/test3](http://localhost:8080/symbols/test3) results in 500 Server error. I would have expected a 404.

`System.ArgumentException: Symbol not found!
   at SoftBeckhoff.Services.BeckhoffServer.ReadSymbol(String name) in /app/Services/BeckhoffServer.cs:line 67
   at SoftBeckhoff.Services.BeckhoffService.GetSymbol(String name) in /app/Services/BeckhoffService.cs:line 46
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()`

**Comment by fbarresi** [comment]
Hi!
Thank you for reporting. Woow! You've opened my first issue on this repo! 
I will fix it.
